{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "transaction-api-operational-luigi.fullname" . }}
  labels:
    {{- include "transaction-api-operational-luigi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "transaction-api-operational-luigi.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable | int }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | int }}
  {{- end }}
  {{- end -}}
